### ISSUE TITLE
The output is truncated to 32Kb

### ISSUE THREAD

**Issue by sangdv** [jcrodriguez-dis/moodle-mod_vpl#102]
The long output is automatically truncated to 32 Kb. How to change this limitation?

**Comment by jcrodriguez-dis** [comment]
Hi sangdv,
you must change the constant JAIL_RESULT_MAX_SIZE to the size that you want (in bytes).
see https://github.com/jcrodriguez-dis/vpl-xmlrpc-jail/blob/18dd1f0a931b8c21f2c703bb3c38917c5146f99d/src/jail_limits.h#L21
After change the size you must run the install-vpl.sh to update the daemon.

I think that this must be control by a configuration parameter. I have add this to the TODO list.

Best regards,
Juan Carlos.

**Comment by sangdv** [comment]
Hi, thank you. That works!
