### ISSUE TITLE
Java submissions do not compile when no jar files are submitted

### ISSUE THREAD

**Issue by rhobincu** [jcrodriguez-dis/moodle-mod_vpl#103]
In v3.3.6, a jar file is mandatory for the submission to compile and run. Otherwise, you get the error message `To run this type of program you need some file with extension "jar"`

**Comment by jcrodriguez-dis** [comment]
Thank you,
Thank very much for your work, rhobincu.
The released V3.3.7 has resolved this and other minor problems.

Best regards,
Juan Carlos.

**Comment by rhobincu** [comment]
Fixed in 3.3.7
