### ISSUE TITLE
Problems with Teacher and Student Role in Moodle

### ISSUE THREAD

**Issue by sehomer** [jcrodriguez-dis/moodle-mod_vpl#108]
Hello,

thank's a lot for this great software. Our professors are faced with the following issue:

When the trainer and the student role are assigned to a person they are not able set up more than one vpl in a course nor to edit existing ones, even if they use the trainer role. Removing the student role solves the problem.

Best regards
Sebastian

**Comment by jcrodriguez-dis** [comment]
Dear @sehomer,
thanks for your bug report.
This problem has been located and will be resolved in the next release of VPL.

Best regards,
Juan Carlos.
