### ISSUE TITLE
Compiler error when using csharp_run.sh in VPL 3.3.8 on newer Mono Version (6.0)

### ISSUE THREAD

**Issue by frankneumann** [jcrodriguez-dis/moodle-mod_vpl#114]
Hello Juan Carlos,

a while ago we installed VPL 3.3.8 on our server. With that came a new csharp_run.sh file using either mcs or csc as C# compiler (as discussed in issue #79 - many thanks). We use a newer Mono framework (6.0) on our server, which contains only csc as compiler.
When I run C# code in that setup, I get an error message from the compiler complaining about a wrong compiler option:

-pkg:dotnet

Apparently, this  is only valid for mcs (the old compiler) but not the new csc one. Could you please correct that error?

Best regards,
Frank

**Comment by jcrodriguez-dis** [comment]
Dear Frank,
thanks very much for the positive feedback and fixes. The next VPL version will omit the wrong compiler option "-pkg:dotnet" when using the csc compiler.

Best regards,
Juan Carlos.
