### ISSUE TITLE
Job for vpl-jail-system.service failed because a timeout was exceeded

### ISSUE THREAD

**Issue by ngoquyenbg** [jcrodriguez-dis/moodle-mod_vpl#118]
I installed jail server 2.6, and i start service with  **sudo service vpl-jail-system start -d 8**, but It take some time and raise the error message:
 Job for vpl-jail-system.service failed because a timeout was exceeded.
See "systemctl status vpl-jail-system.service" and "journalctl -xe" for details

this is /var/log/syslog:
Jan  6 21:21:39 sun vpl-jail-system[19440]: Stopping vpl-jail-system service:                                                            
Jan  6 21:21:39 sun systemd[1]: vpl-jail-system.service: Failed with result 'timeout'.                                                    
Jan  6 21:21:39 sun systemd[1]: Failed to start VPL Jail System Service.  

Please help me to resolve this issue, thank you so much.

**Comment by jcrodriguez-dis** [comment]
Dear Ngoquyenbg,
passing parameters to the start process is deprecated.
You must use the LOGLEVEL parameter to increase log level.
See https://vpl.dis.ulpgc.es/documentation/vpl-jail-system-2.6.0/configuration.html#loglevel
You must report your system details to reproduce the problem.

Best regards,
Juan Carlos.
