### ISSUE TITLE
Unable to connect to remote server

### ISSUE THREAD

**Issue by utkarshmankad** [jcrodriguez-dis/moodle-mod_vpl#120]
I tried writing a simple C code on my Moodle (3.10) + VPL (version 2) setup. When I tried running it, it shown a dialog box showing "connecting....." and it vanished after few seconds. That was all.
Then I saw into browser console (Edge Version 88.0.705.81 (Official build) (64-bit) ), I got the following error message - 
`WebSocket connection to 'ws://demojail.dis.ulpgc.es/1112565614796046/monitor' failed: Error during WebSocket handshake: Unexpected response code: 404`
Can you help me out with this problem ? Also, I am unable to access any resources given on Moodle plugin page.

**Comment by jcrodriguez-dis** [comment]
Hi utkarsh mankad,
if you are using VPL version 2, please update to the last version 3.3.8 or 3.4.0.

This problem is always reproducible?

**Comment by utkarshmankad** [comment]
> Hi utkarsh mankad,
> if you are using VPL version 2, please update to the last version 3.3.8 or 3.4.0.
> 
> This problem is always reproducible?

As suggested, I installed v3.4.0 of the Moodle Plugin, still I am getting the same error, I attaching a small gif reproducing the error. Am I doing something wrong at the initial setup, which I have missed out, sorry the issue can be that lame.
![Screen-Recording-_3-11-2021-12-48-47-PM_](https://user-images.githubusercontent.com/6244858/110750398-69e8b480-8268-11eb-970a-d37526d245d0.gif)

**Comment by jcrodriguez-dis** [comment]
You are using uncypher communication with the Jail-server and It seems that something is interfering. To avoid this, try adapting the plugin general configuration switching the WebSocket protocol option to "Always use encrypted (WSS) WebSocket protocol". Notice that then you need a Jail server with trusted cyphered connections.

![Captura de pantalla 2021-03-11 083405](https://user-images.githubusercontent.com/2072039/110758601-9a1e5c00-8244-11eb-99f8-954e3b0a865c.png)

**Comment by utkarshmankad** [comment]
Thank you very much !!  I was able to make it work with the change suggested.
