### ISSUE TITLE
"More Documentation On This Plugin" link on Moodle.org is broken

### ISSUE THREAD

**Issue by michael-milette** [jcrodriguez-dis/moodle-mod_vpl#125]
The More Documentation On This Plugin link on https://moodle.org/plugins/mod_vpl is broken.

The link says it is going to http://vpl.dis.ulpgc.es/index.php/support but results in:
![image](https://user-images.githubusercontent.com/3808579/138798938-40992467-5a8b-4317-81a2-d4da72448992.png)

Best regards,

Michael Milette

**Comment by jcrodriguez-dis** [comment]
Thanks, Michael.

**Comment by michael-milette** [comment]
Thank you!
