### ISSUE TITLE
PAGE url is missing in view.php

### ISSUE THREAD

**Issue by pavelsokolov** [jcrodriguez-dis/moodle-mod_vpl#129]
It's required to set a proper PAGE url so it can pass the url params. This happens when you need to e.g. edit blocks on a vpl page:

Use case: 
- go to a vpl activity
- edit some block, e.g. change the visibility
- get an error and notice the missing params in the url.

My pull request fixes it https://github.com/jcrodriguez-dis/moodle-mod_vpl/pull/128

**Comment by jcrodriguez-dis** [comment]
Fixed in 8064341ef1c6911aa4133cc74cae7fe28e64e700

Thanks.
