### ISSUE TITLE
Bug in VPL 3.5.0 (2022040512)

### ISSUE THREAD

**Issue by jaume77** [jcrodriguez-dis/moodle-mod_vpl#131]
Hi!

I have installed version 3.5.0 (2022040512) of the module in a Moodle 3.11.5 environment. (Ubuntu, MySQL).

When making a delivery, the following error appears: line 41 of /mod/vpl/forms/evaluation.php: Error thrown

![image](https://user-images.githubusercontent.com/2485232/167200955-cae3da89-065b-4089-9276-6e2dd13ba99a.png)

Checking line 41 of said file, I have observed that a variable ($vpl) is used before instantiating it.

![image](https://user-images.githubusercontent.com/2485232/167201185-2cf14465-7ca8-436a-a595-30aed1ba2904.png)

Changing the order of these lines, the error disappears.

Thanks!
Jaume R.

**Comment by jcrodriguez-dis** [comment]
This bug has been fixed by V3.5.0+
