### ISSUE TITLE
Retrieve submissions through webservices

### ISSUE THREAD

**Issue by nikosdimitrakas** [jcrodriguez-dis/moodle-mod_vpl#136]
Looking at the available web services I see that mod_vpl_open only asks for the Activity id (course_module) and the response is a list of files without any metadata about the student. Could you fix something so that I can either specify the student id as an argument or so that the response can give me all submitted files per student. You can compare with how assign and quiz work, where it is possible to specify the userid (for example in mod_quiz_get_user_attempts) or where the userid is included in the response (for example mod_assign_get_submissions)

**Comment by jcrodriguez-dis** [comment]
Dear nikosdimitrakas,
your enhancement request has been fulfilled in the new V4.0.0 release.

Best regards,
Juan Carlos.

**Comment by nikosdimitrakas** [comment]
Thanks. It works great.
