### ISSUE TITLE
Support userid parameter for mod_vpl_evaluate and mod_vpl_get_result

### ISSUE THREAD

**Issue by FeldrinH** [jcrodriguez-dis/moodle-mod_vpl#138]
The `mod_vpl_open` webservice function recently got support for a `userid` parameter, allowing graders to access any student's results through the webservice API.

It would be nice if support of the `userid` parameter was extended to `mod_vpl_evaluate`, to make it possible to automatically trigger reevaluation of all student submissions from an external service.

(My particular need is that I have an external service that manages and provides test cases to a test script that runs in VPL and I would like to be able to automatically trigger reevaluation of all submissions in VPL when test cases in the external service are updated)

**Comment by jcrodriguez-dis** [comment]
The upcoming VPL release will include the addition of the userid parameter in the mod_vpl_evaluate, mod_vpl_save, and mod_vpl_get_result functions.

**Comment by jcrodriguez-dis** [comment]
Resolved in VPL 4.1.1
