### ISSUE TITLE
Moodle 4.1 Support

### ISSUE THREAD

**Issue by acquaalta** [jcrodriguez-dis/moodle-mod_vpl#143]
Hi,
Could you please add support for Moodle 4.1?
Even if the current version of the plugin would work on Moodle 4.1, an official support would be great.

Thanks even for considering it :-)

**Comment by jcrodriguez-dis** [comment]
The VPL 4.0.1 supports Moodle 4.1
The VPL 4.1.0 supports Moodle 4.2

**Comment by acquaalta** [comment]
Thanks :-)
