### ISSUE TITLE
C# (Csharp) nunit-console: command not found

### ISSUE THREAD

**Issue by nadavkav** [jcrodriguez-dis/moodle-mod_vpl#147]
When running a C# (Csharp) student program, and checking it using some nunit test I created as a teacher, the student gets the following error/warning in the console, when they run their code.
```
./vpl_execution: line 250: nunit-console: command not found
```
After the above message, the nunit tests seem to run without any problems.

Is there an issue here I need to be concerned about?

**Comment by jcrodriguez-dis** [comment]
Dear @nadavkav,

Thanks for your query. The message you're seeing is a warning due to the script not checking if "nunit-console" is installed. Despite the warning, your NUnit tests should run as normal. We've taken note of this and will include a fix in the next VPL release.

**Comment by nadavkav** [comment]
Dear @jcrodriguez-dis , thank you very much for solving this :+1:
