### ISSUE TITLE
php_run.sh generates .router.php with syntax error

### ISSUE THREAD

**Issue by breeze833** [jcrodriguez-dis/moodle-mod_vpl#149]
I discovered that jail/default_scripts/php_run.sh contains an error at line 58.
A right parenthesis is missing, and it causes a syntax error in the generated .router.php.

**Comment by jcrodriguez-dis** [comment]
Thanks for the bug report. The fix will be published in the next release.

**Comment by jcrodriguez-dis** [comment]
Resolved in VPL 4.1.1
