### ISSUE TITLE
Recent activities student filter not working

### ISSUE THREAD

**Issue by pasztuhovd** [jcrodriguez-dis/moodle-mod_vpl#15]
Using Moodle 2.9 with VPL 3.1.4.

When I want to review the recent activities in Home > Course Name > Recent activities and I want to filter the list for **one of the students**, it simply does not work: the page displays not only the selected student's activity but all activities in the specified date range.

**Comment by jcrodriguez-dis** [comment]
Hello pasztuhovd,
Thank for reporting this bug. I will resolve it in next release.
Best regards, 
Juan Carlos

**Comment by pasztuhovd** [comment]
Dear Juan Carlos,

thank you for your quick reply.
This feature is quite important for me, so just let me know if/how I can
contribute in the solution.

Thanks,
Daniel

Hello pasztuhovd,
Thank for reporting this bug. I will resolve it in next release.
Best regards,
Juan Carlos

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/jcrodriguez-dis/moodle-mod_vpl/issues/15#issuecomment-198324278>

**Comment by jcrodriguez-dis** [comment]
The issue has been resolved in last  3.1.5
