### ISSUE TITLE
get_all_user_name_fields() is deprecated. Please use the \core_user\fields API instead

### ISSUE THREAD

**Issue by vahem2lu** [jcrodriguez-dis/moodle-mod_vpl#152]
Using VPL 4.1.0 and deprecation warning from Moodle 4.1.4.

https://github.com/jcrodriguez-dis/moodle-mod_vpl/blob/d9a6ae3ee2ad78a3c75c9920a49d2f72c3ea4faf/vpl_submission.class.php#L587

```
get_all_user_name_fields() is deprecated. Please use the \core_user\fields API instead

    line 3280 of /lib/deprecatedlib.php: call to debugging()
    line 588 of /mod/vpl/vpl_submission.class.php: call to get_all_user_name_fields()
    line 517 of /mod/vpl/views/submissionslist.php: call to mod_vpl_submission::get_grader()
```

**Comment by Astor-Bizard** [comment]
I just want to point out a potential problem with fixing this issue.
There would be a loss of retrocompatibility, as \core_user\fields API class was introduced in Moodle 3.11.

**Comment by vahem2lu** [comment]
You can use newer version of plugin and require newer Moodle for this one. Moodle 3.9 and 3.11 support is about to end anyway.

**Comment by vahem2lu** [comment]
@jcrodriguez-dis do you have any information on this?

**Comment by itsguysmiley** [comment]
I am now getting this error on all Graded assignments using M4.3 and VPL 4.2.1 (latest).  Is there a fix for this?

**Comment by itsguysmiley** [comment]
In moodle 4.3 and VPL 4.2.1, this is the stack trace:
Stack trace:
line 2795 of /lib/deprecatedlib.php: coding_exception thrown
line 610 of /mod/vpl/vpl_submission.class.php: call to get_all_user_name_fields()
line 487 of /mod/vpl/views/submissionslist.php: call to mod_vpl_submission::get_grader()

**Comment by jcrodriguez-dis** [comment]
VPL 4.2.2 Release: Resolution of `get_all_user_name_fields()` Deprecation Warning

- This release addresses the deprecation warning related to the `get_all_user_name_fields()` function as reported in GitHub Issue #152.
- VPL now utilizes \core_user\fields::get_name_fields() if it's available, while maintaining compatibility with previous Moodle versions using get_all_user_name_fields() function if \core_user\fields::get_name_fields() is not available.


Best regards,  
Juan Carlos.
