### ISSUE TITLE
Php - Similarity does not function

### ISSUE THREAD

**Issue by itsguysmiley** [jcrodriguez-dis/moodle-mod_vpl#156]
Please add to similarity/similarity_factory_class.php the key/value 'php' => 'cpp' so that submitted php files can be processed correctly.  It's tested already and works great!

**Comment by jcrodriguez-dis** [comment]
Dear @itsguysmiley,

Thank you for your insightful suggestion. We appreciate your contribution to enhancing the capabilities of our Virtual Programming Lab (VPL).

We are pleased to inform you that we will proceed with implementing the use of the C++ similarity engine for processing PHP files. It is noteworthy that as of VPL version 4.1, we have already modified the underlying architecture to include a base engine for tokenizers that encompasses C++. Therefore, leveraging the C++ similarity engine for PHP submissions is feasible and will not compromise data integrity.

We will incorporate this modification in our next release, as a workaround for the absence of a native PHP similarity engine.
Best regards,
Juan Carlos.
