### ISSUE TITLE
how to install vpl

### ISSUE THREAD

**Issue by newtonmonj** [jcrodriguez-dis/moodle-mod_vpl#16]
Please, av downloaded vpl and jail server, what next, how do i get it to run??

**Comment by jcrodriguez-dis** [comment]
To install the jail server you must follow the instructions in 
http://vpl.dis.ulpgc.es/index.php/support/2014-09-27-15-06-22/40-how-to-install-vpl-jail-system
To install the plugin 
https://docs.moodle.org/28/en/Installing_plugins
More documentation
http://vpl.dis.ulpgc.es/index.php/support/2014-09-27-15-06-22

Best regards,
Juan Carlos
