### ISSUE TITLE
Error prone parsing of proposed grade

### ISSUE THREAD

**Issue by jojoob** [jcrodriguez-dis/moodle-mod_vpl#160]
We had a case were a lecturer [customized the automatic program assessment](https://vpl.dis.ulpgc.es/documentation/vpl-3.4.3+/advancedfeatures.html#evaluation-output-format) to automate the evaluation and grading.
His python script for the evaluation used `print('Grade :=>> {}/100'.format(grade_count))` which produces output like `Grade :=>> 85/100`.

As soon as a submission was evaluated opening the editor led to the following error:
![Screenshot from 2023-11-09 14-41-07](https://github.com/jcrodriguez-dis/moodle-mod_vpl/assets/4180675/9492581d-3626-46be-81b9-9fbe2eccacd7)

```
Default exception handler: Exception - number_format(): Argument #1 ($num) must be of type float, string given Debug:
Error code: generalexceptionmessage
* line 8852 of /lib/moodlelib.php: TypeError thrown
* line 8852 of /lib/moodlelib.php: call to number_format()
* line 682 of /mod/vpl/vpl_submission.class.php: call to format_float()
* line 1308 of /mod/vpl/vpl_submission.class.php: call to mod_vpl_submission->get_grade_core()
* line 229 of /mod/vpl/forms/edit.class.php: call to mod_vpl_submission->get_ce_for_editor()
* line 109 of /mod/vpl/forms/edit.json.php: call to mod_vpl_edit::load()
, referer: https://example.com/mod/vpl/forms/edit.php?id=1234&userid=5678
```

After investigation it turned out that the `/100` part triggered the error.

The analysis of the error showed that [mod_vpl_submission->find_proposedgrade()](https://github.com/jcrodriguez-dis/moodle-mod_vpl/blob/V4.2.2/vpl_submission.class.php#L911) just grabs everything behind `Grade :=>>` until the end of the line. mod_vpl_submission->get_ce_for_editor() passes that value to [mod_vpl_submission->get_grade_core()](https://github.com/jcrodriguez-dis/moodle-mod_vpl/blob/V4.2.2/vpl_submission.class.php#L1308) which in turn [calls Moodles format_float()](https://github.com/jcrodriguez-dis/moodle-mod_vpl/blob/V4.2.2/vpl_submission.class.php#L682) and finally PHPs number_format().

I propose checking the grabbed part to be a number and if it is not showing a descriptive error message to the user. Or at least doing a silent conversation or cast to float to prevent that error message above.
In any case the documentation should include the exact format of the grade line with an example.

---

We are using mod_vpl version 4.2.2 on Moodle 4.1 running with PHP 8.1 and VPL execution server 3.0.1.

**Comment by jcrodriguez-dis** [comment]
Resolved in VPL 4.2.3
