### ISSUE TITLE
4.2.3-Legacy build is not compatible with moodle 3.5 because of hrtime() function

### ISSUE THREAD

**Issue by sandaliero** [jcrodriguez-dis/moodle-mod_vpl#167]
Recent builds use the hrtime() function which was introduced in php 7.3, so the required moodle build number must be 2018120304 (3.6.4).

**Comment by jcrodriguez-dis** [comment]
Dear Andrey Smirnov (@sandaliero),

Thank you for your insightful report. As detailed in the release notes, the current version of the Virtual Programming Lab (VPL) plugin has undergone testing on Moodle versions 3.9 and 3.10. It is also imperative to note that this plugin necessitates PHP 7.4 for its operation.
Considering the potential compatibility issues, I opted for a cautious approach recommending the use of versions that have been tested with the VPL plugin. 

Best regards,
Juan Carlos

**Comment by sandaliero** [comment]
Ok, plugin version 4.2.2 also uses this function and should also rise the moodle version requirements.

**Comment by jcrodriguez-dis** [comment]
Dear Andrey Smirnov (@sandaliero),
Thank you once again for bringing this to our attention. To ensure compatibility of the VPL plugin version 4.2.2, I have updated the list of supported Moodle versions to include those tested, specifically Moodle versions 3.9 and 3.10, 
Best regards, Juan Carlos Rodriguez
Dear Andrey Smirnov (@sandaliero),
Thank you once again for bringing this to our attention. To ensure compatibility of the VPL plugin version 4.2.2, I have updated the list of supported Moodle versions to include those tested, specifically Moodle versions 3.9 and 3.10, 
Best regards, Juan Carlos Rodriguez
