### ISSUE TITLE
Resizing of Output Window in Edit Mode

### ISSUE THREAD

**Issue by chysch** [jcrodriguez-dis/moodle-mod_vpl#174]
When trying to run the program in edit mode the output window is set to 7 text lines and every time I try to resize the window to be bigger it jumps back.

For example:
![image](https://github.com/jcrodriguez-dis/moodle-mod_vpl/assets/39314199/118cb05a-2de5-485d-a5c2-43bf0a9eee8b)

I resized pulling the bottom left corner down and left (it is RTL) and got:
![image](https://github.com/jcrodriguez-dis/moodle-mod_vpl/assets/39314199/89bf608e-51ef-4abe-a0da-4f80c9273ec1)

**Comment by chysch** [comment]
Previous image shows a little more even though I pulled it quite far down.

**Comment by jcrodriguez-dis** [comment]
Dear @chysch,

The terminal window sometimes automatically resets to a smaller size after you attempt to resize it. This behavior ensures that the terminal window remains within the visible area of your screen, preventing it from extending beyond the bounds and becoming difficult to manage.

The program has a built-in mechanism that limits the maximum height of the terminal window to be less than or equal to the height of the editor area. This design is intended to keep the terminal window fully visible and accessible, avoiding situations where the window's borders extend outside the screen's visible zone, making it difficult to move or adjust its size.

If you're looking to have more visible lines in the terminal window, consider making the editor window taller. This approach helps maintain a balance between visibility and usability, ensuring that all parts of the interface remain accessible.

Best regards,
Juan Carlos

**Comment by chysch** [comment]
Thank you so much for your reply. It really clears up the reason for the problem.

This means that the fix should be in the editor window and not in the terminal window and I have brought that up in a separate issue: https://github.com/jcrodriguez-dis/moodle-mod_vpl/issues/175.
