### ISSUE TITLE
Formatting of comments broken in Submission view

### ISSUE THREAD

**Issue by FeldrinH** [jcrodriguez-dis/moodle-mod_vpl#177]
In the latest version (4.2.3), the comments shown under 'Submission view' are not using the VPL formatting.
This was not a problem in the previous version (4.2.2).

Expectation:
![image](https://github.com/jcrodriguez-dis/moodle-mod_vpl/assets/5256211/349059f1-f13f-4a3f-8454-b4531326aa75)

Actual result:
![image](https://github.com/jcrodriguez-dis/moodle-mod_vpl/assets/5256211/e6783a13-634d-411a-95a8-8e4c378dc6ab)

There is a possibly relevant error in the browser console:
![image](https://github.com/jcrodriguez-dis/moodle-mod_vpl/assets/5256211/1e526fe4-c16a-4041-989b-b2e3d4d12c82)
Relevant line in `popover.js`:
![image](https://github.com/jcrodriguez-dis/moodle-mod_vpl/assets/5256211/5685479c-5e0c-4798-96bd-45eef1ec5cc1)

**Comment by jcrodriguez-dis** [comment]
Dear @FeldrinH,

Thank you for bringing this issue to our attention. We have also noticed the problem you described with the 'Submission view' comments not using the VPL formatting in version 4.2.3. I'm pleased to inform you that this issue has been resolved.

The fix will be included in the upcoming VPL release. However, if you need an immediate solution, you can download the branch labeled 4.2.4, which is yet to be officially released. This version contains the necessary fix for the issue you've encountered.

You can find the branch here: [https://github.com/jcrodriguez-dis/moodle-mod_vpl/tree/4.2.4](https://github.com/jcrodriguez-dis/moodle-mod_vpl/tree/4.2.4)

We appreciate your patience and understanding. If you have any further issues or questions, please do not hesitate to reach out.

Best regards,
Juan Carlos
