### ISSUE TITLE
Compatibility Moodle 4.5 ?

### ISSUE THREAD

**Issue by wat973** [jcrodriguez-dis/moodle-mod_vpl#198]
Can you confirm compatibility with moodle version 4.5 ?

**Comment by jcrodriguez-dis** [comment]
Dear wat973,

I can confirm that VPL (Virtual Programming Lab) version 4.2.5 is compatible with Moodle 4.5. This version has been tested across Moodle versions from 3.9 to 4.5. While VPL 4.2.4 is also expected to be compatible with Moodle 4.5, changes in the Behat interface necessitated updates to the tests, which are included in VPL 4.2.5.

Best regards,

Juan Carlos
