### ISSUE TITLE
Installation of VPL server error

### ISSUE THREAD

**Issue by amitojsingh** [jcrodriguez-dis/moodle-mod_vpl#20]
Hello, 
I had successfully installed the moodle and vpl plugin But while installing VPL Jail server encounter with an error. Here's my log file https://gitlab.com/snippets/20192
Also, When I start the server my Internet stop working. 
here's my configuration file https://gitlab.com/snippets/20233
Thanks!

**Comment by jcrodriguez-dis** [comment]
Sorry for the late response.
1) Change the configuration file permissions "/etc/vpl/vpl-jail-system.conf" to 0600 or 0700
2) Set the parameter FIREWALL to 0 in "/etc/vpl/vpl-jail-system.conf"

Best regards.

**Comment by amitojsingh** [comment]
Oh! Its okay thanks for replying I solved it :)
