### ISSUE TITLE
Not accepting urls with ports in jailservers

### ISSUE THREAD

**Issue by sanmen1593** [jcrodriguez-dis/moodle-mod_vpl#21]
I'm adding a server with ports different than `:80` (for example `:8083`) and it isn't work. I do the same installation in another server with port `:80` and it works.

**Comment by jcrodriguez-dis** [comment]
Hello Santiago,
Please, confirm that you write in your VPL plugin configuration the proper URL: e.g.:
http://myserver:8083

Best regards.
Juan Carlos

**Comment by sanmen1593** [comment]
Hi, jcrodriguez

Yes, i'm putting that way: `http://myserver:8083/jail-server`

And i have 

> "jail-server"

In the vpl config of my execution server.

**Comment by jcrodriguez-dis** [comment]
To better spot your problem, please, let me know your jail-server version, your jail-server configuration file and the "list of jail-servers" in your VPL plugin configuration.

Best regards.
Juan Carlos

**Comment by jcrodriguez-dis** [comment]
I haven't be able to reproduce your problem.
Juan Carlos
