### ISSUE TITLE
Compilation fail

### ISSUE THREAD

**Issue by cvnniranjanreddy** [jcrodriguez-dis/moodle-mod_vpl#22]
Hi,

We successfully installed the Jail server and able to connect from moodle. When I execute php or c language code, I am getting below message in moodle insterface.
"I'm sorry, but I haven't a default action to run these type of submitted files"

When I checked the jail server log I get "Compilation fail" message. Can you please help me in fixing this issue.

Below is the complete log from jail server. 

Jun  3 20:58:24 vpl vpl-jail-system[30578]: Client: xx.xx.xx.xxx
Jun  3 20:58:24 vpl vpl-jail-system[30578]: Start server version 2.1.1
Jun  3 20:58:24 vpl vpl-jail-system[30578]: Receiving until 8192 bytes
Jun  3 20:58:24 vpl vpl-jail-system[30578]: Received header 137
Jun  3 20:58:24 vpl vpl-jail-system[30578]: Header :"Host: xx.xx.xx.xxx"
Jun  3 20:58:24 vpl vpl-jail-system[30578]: Header :"Accept: _/_"
Jun  3 20:58:24 vpl vpl-jail-system[30578]: Header :"Content-type: text/xml;charset=UTF-8"
Jun  3 20:58:24 vpl vpl-jail-system[30578]: Header :"User-Agent: VPL 3.1.2"
Jun  3 20:58:24 vpl vpl-jail-system[30578]: Header :"Content-Length: 303"
Jun  3 20:58:24 vpl vpl-jail-system[30578]: http(s) request
Jun  3 20:58:24 vpl vpl-jail-system[30578]: Receiving until 303 bytes
Jun  3 20:58:24 vpl vpl-jail-system[30578]: Execute request 'stop'
Jun  3 20:58:24 vpl vpl-jail-system[30578]: Sending 322
Jun  3 20:58:24 vpl vpl-jail-system[30578]: Send 322
Jun  3 20:58:25 vpl vpl-jail-system[30580]: Client: xx.xx.xx.xxx
Jun  3 20:58:25 vpl vpl-jail-system[30580]: Start server version 2.1.1
Jun  3 20:58:25 vpl vpl-jail-system[30580]: Receiving until 8192 bytes
Jun  3 20:58:25 vpl vpl-jail-system[30580]: Received header 137
Jun  3 20:58:25 vpl vpl-jail-system[30580]: Header :"Host: xx.xx.xx.xxx"
Jun  3 20:58:25 vpl vpl-jail-system[30580]: Header :"Accept: _/_"
Jun  3 20:58:25 vpl vpl-jail-system[30580]: Header :"Content-type: text/xml;charset=UTF-8"
Jun  3 20:58:25 vpl vpl-jail-system[30580]: Header :"User-Agent: VPL 3.1.2"
Jun  3 20:58:25 vpl vpl-jail-system[30580]: Header :"Content-Length: 293"
Jun  3 20:58:25 vpl vpl-jail-system[30580]: http(s) request
Jun  3 20:58:25 vpl vpl-jail-system[30580]: Receiving until 293 bytes
Jun  3 20:58:25 vpl vpl-jail-system[30580]: Execute request 'available'
Jun  3 20:58:25 vpl vpl-jail-system[30580]: Memory requested 67108864
Jun  3 20:58:25 vpl vpl-jail-system[30580]: Status: 'ready'
Jun  3 20:58:25 vpl vpl-jail-system[30580]: Sending 769
Jun  3 20:58:25 vpl vpl-jail-system[30580]: Send 769
Jun  3 20:58:25 vpl vpl-jail-system[30581]: Client: 23.227.133.58
Jun  3 20:58:25 vpl vpl-jail-system[30581]: Start server version 2.1.1
Jun  3 20:58:25 vpl vpl-jail-system[30581]: Receiving until 8192 bytes
Jun  3 20:58:25 vpl vpl-jail-system[30581]: Received header 160
Jun  3 20:58:25 vpl vpl-jail-system[30581]: Header :"Host: xx.xx.xx.xxx"
Jun  3 20:58:25 vpl vpl-jail-system[30581]: Header :"Accept: _/_"
Jun  3 20:58:25 vpl vpl-jail-system[30581]: Header :"Content-type: text/xml;charset=UTF-8"
Jun  3 20:58:25 vpl vpl-jail-system[30581]: Header :"User-Agent: VPL 3.1.2"
Jun  3 20:58:25 vpl vpl-jail-system[30581]: Header :"Content-Length: 4569"
Jun  3 20:58:25 vpl vpl-jail-system[30581]: Header :"Expect: 100-continue"
Jun  3 20:58:25 vpl vpl-jail-system[30581]: http(s) request
Jun  3 20:58:25 vpl vpl-jail-system[30581]: Sending 25
Jun  3 20:58:25 vpl vpl-jail-system[30581]: Send 25
Jun  3 20:58:25 vpl vpl-jail-system[30581]: Receiving until 4569 bytes
Jun  3 20:58:25 vpl vpl-jail-system[30581]: Received 4569
Jun  3 20:58:25 vpl vpl-jail-system[30581]: Execute request 'request'
Jun  3 20:58:25 vpl vpl-jail-system[30581]: Request for process
Jun  3 20:58:25 vpl vpl-jail-system[30581]: Sending 674
Jun  3 20:58:25 vpl vpl-jail-system[30581]: Send 674
Jun  3 20:58:25 vpl vpl-jail-system[30582]: parse files 9
Jun  3 20:58:25 vpl vpl-jail-system[30582]: Write file check C data size 40
Jun  3 20:58:25 vpl vpl-jail-system[30582]: Write file common_script.sh data size 1521
Jun  3 20:58:25 vpl vpl-jail-system[30582]: Write file vpl_environment.sh data size 101
Jun  3 20:58:25 vpl vpl-jail-system[30582]: Write file vpl_run.sh data size 385
Jun  3 20:58:25 vpl vpl-jail-system[30582]: Reading parms
Jun  3 20:58:25 vpl vpl-jail-system[30582]: Compilation
Jun  3 20:58:25 vpl vpl-jail-system[30582]: child pid 30583
Jun  3 20:58:25 vpl vpl-jail-system[30583]: chrooted "/jail"
Jun  3 20:58:25 vpl vpl-jail-system[30583]: change user to 15159
Jun  3 20:58:25 vpl vpl-jail-system[30582]: New redirector state 0 => 2
Jun  3 20:58:25 vpl vpl-jail-system[30582]: Program end or I/O error: Success 16 (POLLHUP ).
Jun  3 20:58:25 vpl vpl-jail-system[30582]: New redirector state 2 => 5
Jun  3 20:58:25 vpl vpl-jail-system[30582]: Compilation fail
Jun  3 20:58:26 vpl vpl-jail-system[30584]: Client: xx.xx.xx.xxx
Jun  3 20:58:26 vpl vpl-jail-system[30584]: Start server version 2.1.1
Jun  3 20:58:26 vpl vpl-jail-system[30584]: Receiving until 8192 bytes
Jun  3 20:58:26 vpl vpl-jail-system[30584]: Received header 535
Jun  3 20:58:26 vpl vpl-jail-system[30584]: Header :"Host: xx.xx.xx.xxx"
Jun  3 20:58:26 vpl vpl-jail-system[30584]: Header :"Connection: Upgrade"
Jun  3 20:58:26 vpl vpl-jail-system[30584]: Header :"Pragma: no-cache"
Jun  3 20:58:26 vpl vpl-jail-system[30584]: Header :"Cache-Control: no-cache"
Jun  3 20:58:26 vpl vpl-jail-system[30584]: Header :"Upgrade: websocket"
Jun  3 20:58:26 vpl vpl-jail-system[30584]: Header :"Origin: http://xxxx.com"
Jun  3 20:58:26 vpl vpl-jail-system[30584]: Header :"Sec-WebSocket-Version: 13"
Jun  3 20:58:26 vpl vpl-jail-system[30584]: Header :"User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
Jun  3 20:58:26 vpl vpl-jail-system[30584]: Header :"Accept-Encoding: gzip, deflate, sdch"
Jun  3 20:58:26 vpl vpl-jail-system[30584]: Header :"Accept-Language: en-GB,en-US;q=0.8,en;q=0.6"
Jun  3 20:58:26 vpl vpl-jail-system[30584]: Header :"Sec-WebSocket-Key: 4/5E7dpCh0/fR/eS0KcWWQ=="
Jun  3 20:58:26 vpl vpl-jail-system[30584]: Header :"Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits"
Jun  3 20:58:26 vpl vpl-jail-system[30584]: Sending 129
Jun  3 20:58:26 vpl vpl-jail-system[30584]: Send 129
Jun  3 20:58:26 vpl vpl-jail-system[30584]: Sending 94
Jun  3 20:58:26 vpl vpl-jail-system[30584]: Send 94
Jun  3 20:58:26 vpl vpl-jail-system[30584]: Sending 8
Jun  3 20:58:26 vpl vpl-jail-system[30584]: Send 8
Jun  3 20:58:26 vpl vpl-jail-system[30584]: Sending 2
Jun  3 20:58:26 vpl vpl-jail-system[30584]: Send 2
Jun  3 20:58:26 vpl vpl-jail-system[30584]: Cleaning
Jun  3 20:58:26 vpl vpl-jail-system[30584]: Sttoping prisoner process
Jun  3 20:58:26 vpl vpl-jail-system[30585]: change user to 15159
Jun  3 20:58:26 vpl vpl-jail-system[30584]: Remove prisoner home (15159)
Jun  3 20:58:26 vpl vpl-jail-system[30584]: Cleaning monitor
Jun  3 20:58:26 vpl vpl-jail-system[30584]: Sttoping prisoner process
Jun  3 20:58:26 vpl vpl-jail-system[30586]: change user to 15159
Jun  3 20:58:26 vpl vpl-jail-system[30584]: Remove prisoner home (15159)
Jun  3 20:58:26 vpl vpl-jail-system[30584]: Received 6

**Comment by jcrodriguez-dis** [comment]
Hi Niranjan,
From the log that you show here, I notice some issues:
1) The selection of programming language (by the system) is based on the file name extension. If you don't set a file extensión the system will not know what programming language are you using.
2) Also,  I recommend you to use the last version of both the jail server and the moodle plugin.

Best regards.
Juan Carlos.
P.D.: solution: rename your file "check C" to "check.c". Don't use spaces in file names and "C" has different effect than "c".

**Comment by cvnniranjanreddy** [comment]
Thank You for reply.

I identified above issue and solved it. But now we are getting "The execution server needs to install "php5" to run this type of program" message when we Run the script from moodle.

Can you please help us in fixing above issue.

**Comment by jcrodriguez-dis** [comment]
Before go further, please tell me your versions of Moodle, VPL, jail server and jail server OS.
Best regards.

**Comment by cvnniranjanreddy** [comment]
Sure,

Below are the Details.

Moodle: 2.7.2
Moodle VPL Module: 3.1.4(2015080600)
Jail Server OS: CentOS 7.1
Jail Server: 2.2.0

Please let me know if you need any further details.

**Comment by jcrodriguez-dis** [comment]
The current PHP default script is not suitable for your Jail Server OS. I am working to resolve the issue ASAP.
Best regard

**Comment by cvnniranjanreddy** [comment]
Ok. Thank you, I will wait for that.

I know that VPL will not support SAS and R Language. If implementation of SAS and R language is in your roadMap, please let us know, I will be more happy in implementing.

It will be more helpful if you provide any documentation related to the implementation.

**Comment by jcrodriguez-dis** [comment]
This issue has been resolved in VPL 3.2-beta. Please recheck your problem in the new version.
