### ISSUE TITLE
Image is not correctly restored

### ISSUE THREAD

**Issue by antonio-c-mariani** [jcrodriguez-dis/moodle-mod_vpl#23]
Steps:
1. Create a new vpl activity;
2. Add a title;
3. Add a description that includes an image using the "insert/edit image" button from de html editor;
4. Make a activity backup;
5. Restore the backup into the same course;
6. The image is not shown at the description. 
I'm using Moodle 3.0 and VPL module version 2015080600 (3.1.4).

A.C.Mariani

**Comment by jcrodriguez-dis** [comment]
Hello Antonio,
I will try to reproduce the problem.

**Comment by jcrodriguez-dis** [comment]
It's confirmed, there is a bug.
The decode of the URL of the image from the backup is incorrect.
As a workaraung you can use embeded images insteand.
I will try to resolve the problem before the next release.

**Comment by jcrodriguez-dis** [comment]
Resolved in commit
https://github.com/jcrodriguez-dis/moodle-mod_vpl/commit/ae49fe367627b30210775769e796ee13fb788d9b
