### ISSUE TITLE
Problem with locale on grades

### ISSUE THREAD

**Issue by antonio-c-mariani** [jcrodriguez-dis/moodle-mod_vpl#24]
Hi,

Our Moodle default language is pt_br (Português - Brasil). When I try to set a student grade as "7,5" (see image 1), the result grade is "7 / 10", without the decimal part (see image 2). It seems there is some problem with localized grades. 

I'm using Moodle 3.0 and VPL module version 2015080600 (3.1.4).

![vpl1](https://cloud.githubusercontent.com/assets/10731910/17947860/da054a8c-6a24-11e6-85e4-8e3bb2f6d6af.png)

![vpl2](https://cloud.githubusercontent.com/assets/10731910/17947870/e24c7242-6a24-11e6-9bbf-8c6c7a984fb4.png)

A.C.Mariani

**Comment by jcrodriguez-dis** [comment]
It's a bug. Thanks you.
