### ISSUE TITLE
Problem with group name

### ISSUE THREAD

**Issue by charliedaly** [jcrodriguez-dis/moodle-mod_vpl#26]
I am using vpl 2016071800 (3.1.5)

The students create groups and select a group name. They then submit a VPL programming exercise.
Some students created names which contain a single quote ('). When they do this, the testing process fails with a message:
vpl_environment.sh: line 11: unexpected EOF while looking for matching `'' 
vpl_environment.sh: line 14: syntax error: unexpected end of file 

In one case, the student was told that all tests passed but received a mark of 10 out of 100.

**Comment by jcrodriguez-dis** [comment]
Hello Charlie,
thanks for your bug report.
This problem has been resolved with https://github.com/jcrodriguez-dis/moodle-mod_vpl/commit/5dc8fa1e21e8ceee3ff6434a3a2cb689526fb21f#diff-ee976a36829515ade3fef48050d87ef6

Best regards.
