### ISSUE TITLE
jail-system: compiling python?

### ISSUE THREAD

**Issue by ewout** [jcrodriguez-dis/moodle-mod_vpl#3]
I installed the vpl-jail, the connection seems to be ok (http://200.144.255.219:8082/OK) but running a first python program seems to hang. Running the jail with -d 8 gives

Sending 129
Sep 17 22:09:39 ubuntu14 vpl-jail-system[23923]: Send 129
Sep 17 22:09:39 ubuntu14 vpl-jail-system[23923]: Monitor compiling
Sep 17 22:09:39 ubuntu14 vpl-jail-system[23923]: Sending 21
Sep 17 22:09:39 ubuntu14 vpl-jail-system[23923]: Send 21
Sep 17 22:09:40 ubuntu14 vpl-jail-system[23923]: Sending 28
Sep 17 22:09:40 ubuntu14 vpl-jail-system[23923]: Send 28
Sep 17 22:09:41 ubuntu14 vpl-jail-system[23923]: Sending 28
Sep 17 22:09:41 ubuntu14 vpl-jail-system[23923]: Send 28
Sep 17 22:09:42 ubuntu14 vpl-jail-system[23923]: Sending 28

Any idea how to debug this further?

**Comment by jcrodriguez-dis** [comment]
This error is due to a lack of some files related with locale in the etc folder of the jail. This problem has been resolved in the 2.1 version
