### ISSUE TITLE
The tested program has the privilegs to read/write files that involved in the cheak (like evaluate.cases)

### ISSUE THREAD

**Issue by 123yagel** [jcrodriguez-dis/moodle-mod_vpl#35]
as I did in the attached program in c++:
[cheat_VPL.txt](https://github.com/jcrodriguez-dis/moodle-mod_vpl/files/625938/cheat_VPL.txt)

(I used txt because of github..)

**Comment by jcrodriguez-dis** [comment]
Thanks for your bug report.
This problem affects to all versions of VPL. The solution is to replace vpl_evaluate.cpp for the new version patched.
See https://github.com/jcrodriguez-dis/moodle-mod_vpl/commit/64bded00cd0f52047242f5c08cecb674662f221f
