### ISSUE TITLE
Submitted files not saved

### ISSUE THREAD

**Issue by jderriks** [jcrodriguez-dis/moodle-mod_vpl#37]
Strange problem. Submitting files by dragging or uploading files does not work (on our system with latest VPL and Moodle 3.2 Build: 20161205).

VPL shows files as submitted but when downloading the zip is zero bytes and submission view is empty. Is this a VPL or Moodle issue? Normal activities where files are submitted work fine.

How can I track/check/debug the VPL file submission code?
Debugging output only shows some warnings:

> Warning: strlen() expects parameter 1 to be string, array given in /srv/acc-moodle.hva.nl/htdocs/mod/vpl/vpl.class.php on line 599
> 
> Warning: fwrite() expects parameter 2 to be string, array given in /srv/acc-moodle.hva.nl/htdocs/mod/vpl/filegroup.class.php on line 165
> Saved

> [Tue Dec 20 15:31:44.795944 2016] [:error] [pid 19795] [client xx12627] PHP Warning:  var_export does not handle circular references in /srv/acc-moodle.hva.nl/htdocs/lib
> /classes/shutdown_manager.php on line 83, referer: https://acc-moodle.hva.nl/mod/vpl/view.php?id=8&userid=4688
> [Tue Dec 20 15:31:44.795990 2016] [:error] [pid 19795] [client xx:12627] PHP Warning:  var_export does not handle circular references in /srv/acc-moodle.hva.nl/htdocs/lib
> /classes/shutdown_manager.php on line 83, referer: https://acc-moodle.ict.hva.nl/mod/vpl/view.php?id=8&userid=4688
> [Tue Dec 20 15:31:44.796112 2016] [:error] [pid 19795] [client xx2627] PHP Warning:  var_export does not handle circular references in /srv/acc-moodle.hva.nl/htdocs/lib/classes/shutdown_manager.php on line 83, referer: https://acc-moodle.hva.nl/mod/vpl/view.php?id=8&userid=4688

**Comment by jcrodriguez-dis** [comment]
Hello Derriks,
I am reviewing this issue and I will give you a response as soon as possible.

Best Regards,
Juan Calros

**Comment by jcrodriguez-dis** [comment]
Please check VPL 3.2.3. This bug fix version must resolve your problem.
https://github.com/jcrodriguez-dis/moodle-mod_vpl/tree/v3.2.3

**Comment by jderriks** [comment]
It works! Thanks for the fix!
Github beats https://moodle.org/plugins/ updates.
