### ISSUE TITLE
Http not implemented error in moodle after VPL installation

### ISSUE THREAD

**Issue by shincyunni** [jcrodriguez-dis/moodle-mod_vpl#44]
After installing vpl server in my system it shows an error "HTTP not implemented"
It returns okay when I try the url //172.16.13.222/OK but not work with /172.16.13.222/moodle/

I am new to moodle and don't know want to do.

**Comment by leder11011** [comment]
you need a configured URL for vpl-server, e. g. http://192.16.13.222/jails,
and separate moodle installation http://ip.address/moodle that refers in its vpl-plugin configuration to the jails server.

**Comment by shincyunni** [comment]
Okay. Thank You
