### ISSUE TITLE
Renaming

### ISSUE THREAD

**Issue by wgalam** [jcrodriguez-dis/moodle-mod_vpl#46]
Hi, i'm using vpl plugin in a moodle site, but i heaving a problem when renaming an vpl activity. The name only change in course window, but in gradebook the original name still unchanged.
I also tried on vpl demo site and the problem occurs also.

Thank's!

**Comment by jcrodriguez-dis** [comment]
Hello wgalam,
yes, this problem has been there for a long time. After searching for the origin of the problem, I thing that it is related to the support of the Moodle grade API by VPL.
Best regards,
Juan Carlos

**Comment by wgalam** [comment]
I thinking about to create a trigger in database started when update the
table mdl_vpl. Do you know wich ID's i should use as keys between mdl_vpl
and mdl_grade_item?

Best regards,







2017-05-29 14:09 GMT-03:00 jcrodriguez-dis <notifications@github.com>:

**Comment by jcrodriguez-dis** [comment]
The solution here is to implement the functions
vpl_grade_item_update
vpl_update_grades
these functions will be called whe the name are update.
This solution will be released in VPL 3.3
Best regards,
Juan Carlos.

**Comment by wgalam** [comment]
Thank you, Juan Carlos.

Best Regards!







2017-05-30 9:48 GMT-03:00 jcrodriguez-dis <notifications@github.com>:

**Comment by jcrodriguez-dis** [comment]
Hello wgalam,
This bug is resolved in V3.3.

**Comment by wgalam** [comment]
Thank you, Jcrodriguez!







2017-12-06 11:59 GMT-03:00 jcrodriguez-dis <notifications@github.com>:
