### ISSUE TITLE
¿Cómo puedo descargar el plugin?

### ISSUE THREAD

**Issue by alphonse92** [jcrodriguez-dis/moodle-mod_vpl#47]
Revisando el directorio de plugins encontré el de VPL. Sin embargo no puedo descargarlo desde allí.
![image](https://user-images.githubusercontent.com/18203585/28502457-6cbce29c-6fb8-11e7-978f-285ea76291bf.png)

¿Me podrías indicar el proceso para descargar el plugin?. Para mi trabajo de tesis den mi actual universidad quisiera agregar unas nuevas funcionalidades a VPL. Gracias por tu pronta respuesta

**Comment by jcrodriguez-dis** [comment]
Estimado Alejandro,
pulsando en el botón [versions] podrás descargar la versión que necesites. También puedes descargar la versión en desarrollo v3.3dev desde https://github.com/jcrodriguez-dis/moodle-mod_vpl/archive/v3.3dev.zip
Más información en http://vpl.dis.ulpgc.es

Un saludo,
Juan Carlos
