### ISSUE TITLE
Help me with this issue

### ISSUE THREAD

**Issue by sathizzh** [jcrodriguez-dis/moodle-mod_vpl#48]
When I create my own .php file and use this 

> require_once(dirname(__FILE__).'/../vpl.class.php');
and when i run that file on browser. It displays nothing. Whats the reason.

**Comment by jcrodriguez-dis** [comment]
Hello sathizzh,
you must give details, whats is the contents of own.php?. I must say that the inclusion of vpl.class.php shows nothing.

Best regards,
Juan Carlos.

**Comment by sathizzh** [comment]
Thanks for the reply. I have sorted it out.
