### ISSUE TITLE
CR-LF in all files causes problems on U14.04

### ISSUE THREAD

**Issue by dirkcgrunwald** [jcrodriguez-dis/moodle-mod_vpl#5]
I'm doing a fresh install (using a fork) on an Ubuntu 14.04 system.

I'm running into build problems. The first set are cause by the use of DOS-style CR-LF line endings.
I "fixed" these using dos2unix, but this changes almost all the files (....make git practically useless...)

I also had to chmod ugo+x the *.sh, *-sh and configure scripts. Permissions weren't recorded.

Lastly, I run into the following error. From my quick look, I would think that I wouldn't be producing the -centos variant because I'm running on Ubuntu.

Checking installed software                                                     
Compiling vpl-jail-server                                                       
make[2]: *** No rule to make target `vpl-jail-system.centos', needed by `all-am\
'.  Stop.                                                                       
make[1]: *** [all-recursive] Error 1                                            
make: *** [all] Error 2                                                         
Updating installation => /etc/vpl  

But in Makefile, I see

dist_pkgdata_DATA = vpl-jail-system.centos vpl-jail-system.ubuntu vpl-xmlrpc-ja\
il.conf vpl-xmlrpc-jail.xinetd

**Comment by jcrodriguez-dis** [comment]
The version 2.1 is now stable.
