### ISSUE TITLE
Problema al probar la jaula de ejecución.

### ISSUE THREAD

**Issue by alphonse92** [jcrodriguez-dis/moodle-mod_vpl#51]
Cordial saludo @jcrodriguez-dis 

Intenté installar la jaula de ejecución, sin embargo tengo problemas al querer probarla como dice en el sitio
http://server:PORT/OK and https://server:SECURE_PORT/OK, pero no obtengo respuesta del servidor de la jaula de ejecución. También me parece raro que el servicio inicie normalmente si coloco la jaula de ejecución a correr en el puerto 80 (al igual que httpd) mientras httpd está ejecutandose.

Mi servidor es centOS 7

![image](https://user-images.githubusercontent.com/18203585/30245837-9bea89a2-95ab-11e7-9ffd-b098ba90dc91.png)

Adjunto mi archivo de configuración y mi archivo de log 
[vpl-jail-system.conf.txt](https://github.com/jcrodriguez-dis/moodle-mod_vpl/files/1290227/vpl-jail-system.conf.txt)

[vpl-jail-service.log.txt](https://github.com/jcrodriguez-dis/moodle-mod_vpl/files/1290229/vpl-jail-service.log.txt)

Edit 1: desactive el firewall y SElinux y sin embargo el problema persiste.
Edit 2: la jaula se instala efectivamente en centOS, el servicio se activa pero falla. Por otro lado en ubuntu 14.04.05 funciona perfectamente.

**Comment by jcrodriguez-dis** [comment]
Hello Alejandro,
the screenshot seems that it is a problem related to the  configuration of the system or the service is not starting.

please, try using the last vpl-jail-system version 2.2.2
http://vpl.dis.ulpgc.es/releases/vpl-jail-system-2.2.2.tar.gz
If still don't work increase the loglevel in the config file and show here the generated log.

Best regards,
Juan Carlos.
