### ISSUE TITLE
Problem with order of the required files

### ISSUE THREAD

**Issue by aivarannamaa** [jcrodriguez-dis/moodle-mod_vpl#52]
I had a VPL exercise without required files. I submitted two files under my account: ylesanne2.py and ylesanne1.py (in this order).

Later I specified required files ylesanne1.py and ylesanne2.py (in this order).

Now I can't save the submitted files anymore:

![image](https://user-images.githubusercontent.com/1802/30955916-097e2b90-a43e-11e7-96bc-74d9aba35327.png)

VPL version: 3.2.4

**Comment by aivarannamaa** [comment]
Also, when I have a submission with one file, and I later add one required file, then I can't submit the missing file anymore.

**Comment by jcrodriguez-dis** [comment]
Hello Aivar.
yes, this is a known and annoying bug in V3.2.4.
This bug has been resolved in 3.3 version.
I will keep it open until the 3.3 release.

Best regards,
Juan Carlos

**Comment by jcrodriguez-dis** [comment]
Hello Aivar,
this bug is resolved in V3.3.
