### ISSUE TITLE
Cannot force jail_servers setting.

### ISSUE THREAD

**Issue by fwsl** [jcrodriguez-dis/moodle-mod_vpl#54]
Hi,

I'm using config file to force most of the nondefault settings in moodle. I've tried to force the settings for the VPL and all but one work as expected. I've got problem with jail_servers setting which is not forced. Maybe textarea setting should be forced in a different way.
Could you look if this works on your installation?

You need to paste one of these into config.php First one should only force the jail_servers setting, second should force all plugin settings

`$CFG->forced_plugin_settings = array('mod_vpl'=>array('jail_servers ' =>'http://demojailTEST_TEST.dis.ulpgc.es'));
`

`$CFG->forced_plugin_settings = array('mod_vpl'      =>array('maxfilesize' => '4194304',
                                'maxexetime' => '1920',
                                'maxexefilesize' => '134217728',
                                'maxexememory' => '536870912',  
                                'maxexeprocesses' => '200',  
                                'defaultfilesize' => '65536',
                                'defaultexetime' => '240',
                                'defaultexefilesize' => '67108864',
                                'defaultexememory' => '67108864',  
                                'defaultexeprocesses' => '100',  
                                'jail_servers ' =>'http://demojailTEST_TEST.dis.ulpgc.es',
                                'acceptcertificates' => '1',
                                'websocket_protocol' => 'depends_on_https',
                                'proxy' => '',
                                'use_watermarks' => '0',
                                'discard_submission_period' => '60')
        );

`

**Comment by jcrodriguez-dis** [comment]
Hello fwsl,
please, remove the space at the end of the string 'jail_servers '.

best regards,
Juan Carlos.

**Comment by fwsl** [comment]
Hello Juan

Thanks, not sure how I've missed it. :man_facepalming: 

Cheers
Grzesiek
