### ISSUE TITLE
support Moodle 3.3 and 3.4

### ISSUE THREAD

**Issue by dluschan** [jcrodriguez-dis/moodle-mod_vpl#55]
Hello.
Plugin vpl is not available for installation with Moodle 3.3 and 3.4 versions through menu “Plugins -> Install plugins -> Install plugins from the Moodle directory” =(
Do you plan to add support of these Moodle versions? When? If not, will update and remove will be available for plugin after manual install through “Install plugin from ZIP file“?
Thank you.

**Comment by jcrodriguez-dis** [comment]
Yes, we are working to finishing and test VPL 3.3. This new version will be compatible with 3.3 and 3.4. We hope to do a release this week.

Best regards.

**Comment by dluschan** [comment]
It happened! =)
Thank you very much!
