### ISSUE TITLE
explain similarity scores

### ISSUE THREAD

**Issue by hthuwal** [jcrodriguez-dis/moodle-mod_vpl#56]
Hi, can you please explain what the similarity scores mean.

https://github.com/jcrodriguez-dis/moodle-mod_vpl/blame/310d44aaa80e6a0dc2c4c1a1be3d7ee5709c2185/similarity/similarity_base.class.php#L300-L361

**Comment by jcrodriguez-dis** [comment]
Hello hthuwal,
you can read the following post at the VPL forum
https://moodle.org/mod/forum/discuss.php?d=154988#p1282637

**Comment by hthuwal** [comment]
Thanx!
