### ISSUE TITLE
Syntax highlighting not working for c file (*.c)

### ISSUE THREAD

**Issue by philipr-za** [jcrodriguez-dis/moodle-mod_vpl#60]
Good day,

So I just installed the new VPL package but now the syntax highlighting for C files is not turning on. I cant seem to find any setting to enable it and it works for python and octave files.

Thanks,
Philip Robinson

**Comment by jcrodriguez-dis** [comment]
Hello Philip,
sorry for the delay answering your question. I lost the github email.

You don't need to switch any option, all the syntax highlighting is on by default, and cannot be switched off.
Notice that the syntax highlighting is based on the file name extension. The extensions related with C and C++ are 'c', 'C', 'cc', 'cpp', 'hxx', and 'h'.
Please, tell me your VPL and Moodle version.

Is your problem reproducible at the demo site?

Best regards,
Juan

**Comment by philipr-za** [comment]
It was on a brand new install of Moodle 3.4.1 and VPL 3.3.2. What I ended up doing was a full reinstall of VPL and I also flushed my cache's as I had been working with an older VPL recently so perhaps the cached javascript files were the issue.
Either way the reinstall fixed it. I will mark this issue as closed.
Thanks for the response.
Philip
