### ISSUE TITLE
Question about implementation of  vpl_submission_CE.class.php:prepare_execution

### ISSUE THREAD

**Issue by alphonse92** [jcrodriguez-dis/moodle-mod_vpl#62]
What is the porpouse for lines between 153 - 195 

https://github.com/jcrodriguez-dis/moodle-mod_vpl/blob/ee2d1bf28d7f1643c419775d7c6ce205a9cc61e0/vpl_submission_CE.class.php#L153

If $list will be overwrited in the line 195 ?

https://github.com/jcrodriguez-dis/moodle-mod_vpl/blob/ee2d1bf28d7f1643c419775d7c6ce205a9cc61e0/vpl_submission_CE.class.php#L195

I think its allows to students overrwrite the teacher's execution files. Can u explain me?

**Comment by jcrodriguez-dis** [comment]
Hello Alphonse,
thanks for your review, I am sure that there are bugs hidden in the code of VPL. Anyway, may be better review the version with the highest version number, I apologise but the master branch is outdated.
Best regards,
Juan Carlos.
