### ISSUE TITLE
Description tab doesn't render Latex formulas

### ISSUE THREAD

**Issue by rhobincu** [jcrodriguez-dis/moodle-mod_vpl#63]
When no files exist in the online editor (for example when you first attempt an assignment), Latex formulas aren't rendered correctly in the description tab. Even after creating a new file, formulas still don't appear unless the page is refreshed.

**Comment by dktcoding** [comment]
Have you tried to move the LaTeX filter after HTML Tidy (and Syntax Highlight if you use it)? I use a lot of formulas in VPL and this solved my problem.

![image](https://user-images.githubusercontent.com/709639/39900592-3aa8b8dc-5499-11e8-9352-9f0d355eb2b1.png)

**Comment by rhobincu** [comment]
Hello, sorry for the late reply. The problem isn't on the description tab of the VPL assignment, but the description tab on the right side of the online editor editor. 
![image](https://user-images.githubusercontent.com/8833880/40070346-7ddf5a30-5876-11e8-940a-d2a578a7745b.png)

**Comment by jcrodriguez-dis** [comment]
Resolved in VPL 3.3.5 just released
