### ISSUE TITLE
Some moodle deprecation warnings

### ISSUE THREAD

**Issue by jderriks** [jcrodriguez-dis/moodle-mod_vpl#7]
Moving to a new system with the latest Moodle version Moodle 2.9+ (Build: 20150618) and VPL plugin 2015020103 	3.1.2.

Then with Moodle debug setting on "Developer" it shows some warnings. Nothing serious.

Function moodleform_mod::add_intro_editor() is deprecated, use moodleform_mod::standard_intro_elements() instead.

    line 700 of /course/moodleform_mod.php: call to debugging()
    line 45 of /mod/vpl/mod_form.php: call to moodleform_mod->add_intro_editor()
    line 191 of /lib/formslib.php: call to mod_vpl_mod_form->definition()
    line 86 of /course/moodleform_mod.php: call to moodleform->moodleform()
    line 255 of /course/modedit.php: call to moodleform_mod->moodleform_mod()

**Comment by jcrodriguez-dis** [comment]
Thanks for your bug report.
I will address this issue as soon as possible.

**Comment by jcrodriguez-dis** [comment]
After reviewing the problem, that it is very easy to resolve, we think that it is better to keep using the deprecated method. If we use the new method, the new VPL version will be usable only in Moodle 2.9 and onwards. We don't want to create a new VPL branch to remove this message. Sorry for the annoying message in debug mode but we think that it is better than keeping many VPL versions updated. Of course, we will use the new method in the Moodle 2.11 version when the deprecated method will be removed. You must consider that the current obsolete method in Moodle 2.9 calls the new one.

Best regards.

**Comment by jcrodriguez-dis** [comment]
Rethinking the problem, I have found a solution to remove the deprecated message. Now VPL checks the Moodle versión to use the deprecated or the new method.
The problem has been resolved in VPL 3.1.3.
Already available here in Github

Best regards
