### ISSUE TITLE
Bug when post_max_size is 0

### ISSUE THREAD

**Issue by jcrodriguez-dis** [jcrodriguez-dis/moodle-mod_vpl#74]
Reported by Brian Sea,
vpl_get_max_post_size() in locallib.php doesn't take into account that post_max_size in the php.ini could be zero -- as in "no limit."  As a result, VPL doesn't allow for the setting of a max file size.

**Comment by olberger** [comment]
For reference, I tend to think I've been bitten by that bug, as per https://moodle.org/mod/forum/discuss.php?d=434080

Thanks in advance.

**Comment by jcrodriguez-dis** [comment]
Issue resolved in V3.5 32d77a14.
