### ISSUE TITLE
"No grade" VPL assignments appear in the gradebook

### ISSUE THREAD

**Issue by rhobincu** [jcrodriguez-dis/moodle-mod_vpl#77]
I have several VPL activities in my courses that are just for practice and as such, they have no points assigned to them (selected grade type is None in activity settings). However, with Moodle version 3.5.2+ (Build: 20180914) and latest version of VPL, these activities appear as Uncategorized grades in the gradebook, with a total of 100 points each. If I edit the activity and then save it without changing anything, the grade disappears from the gradebook only to reappear later. I don't know what triggers it. 

This happens in two different deployments.

**Comment by jcrodriguez-dis** [comment]
Sorry  rhobincu, I have not been able to reproduce the issue.
If you have more details about the problem, please let us know., it will help us to spot it.

Best regards,
Juan Carlos.

**Comment by rhobincu** [comment]
According to 3.3.7 release notes: 
_Gradebook. The patch removes ghost empty grades appearing in the gradebook._

After upgrading the plugin, I haven't seen any unwanted grades in the gradebook anymore.
