### ISSUE TITLE
"rate" a task without selected rating

### ISSUE THREAD

**Issue by GaRaOne** [jcrodriguez-dis/moodle-mod_vpl#78]
We have received an error report from one of our users and would like to forward it to you.

Starting with the original german text and followed by the english translation:

-----------------------

Liebes e-Learning-Team,

während meiner Tätigkeit beim Bewerten von Studierenden ist mir eine Fehler im
VPL-Modul aufgefallen.

Beim Bewerten einer Aufgabe öffnet sich das neue Fenster mit den Möglichkeiten,
eine Bewertung zu vergeben, sh. Anlage. Hier ist jedoch der Button "Bewerten" 
und auch "Bewerten & nächstes" aktiv, obwohl keine Bewertung ausgewählt ist.
Wenn man aus versehen auf Bewerten klickt, bevor eine Bewertung gewählt wird,
löst dies eine Aktion aus und bewertet die Leistung mit einer nicht
vorhersehbarer Bewertung. Das müsste eigentlich blockiert sein.

Ich hoffe, das lässt sich mit dem nächsten Update beheben.

Vielen Dank im Voraus

-----------------------

Dear e-learning team,

during my work as a student evaluator, I have made a mistake in the
VPL module.

When evaluating a task, the new window with the possibilities opens,
to assign a rating, see Appendix. But here is the button "Rate". 
and also "Rate & Next" active, although no rating is selected.
If you accidentally click on Rate before selecting a rating,
this triggers an action and evaluates the service with a non
predictable valuation. That should actually be blocked.

I hope this can be fixed with the next update.

Many thanks in advance

-----------------------
![bug_vpl](https://user-images.githubusercontent.com/9949794/51980710-24eed300-2491-11e9-8311-caf6771f2453.jpg)

**Comment by jcrodriguez-dis** [comment]
Hello GaRaOne,
Thanks for your bug report.
The bug is confirmed and is considered important. It will be resolved in the next release.

Best regards,
Juan Carlos.

**Comment by jcrodriguez-dis** [comment]
Resolved in VPL 3.3.5 just released
