### ISSUE TITLE
unexpected EOF

### ISSUE THREAD

**Issue by mariocav** [jcrodriguez-dis/moodle-mod_vpl#8]
Hello,

there is a possible issue when using a specific language and submitting a VPL activity. The module outputs:

```
vpl_environment.sh: line 7: unexpected EOF while looking for matching `''
vpl_environment.sh: line 10: syntax error: unexpected end of file
```

I think the problem comes with the file **vpl_submission_CE.class.php**. Line 233:

```
$info .='export VPL_COMPILATIONFAILED=\''.get_string('VPL_COMPILATIONFAILED',VPL)."'\n";
```

should be replaced with:

```
$info .='export VPL_COMPILATIONFAILED=\''.get_string('VPL_COMPILATIONFAILED',VPL)."\n";
```

Removing the single quote inside the last part (**'\n** to **\n**) solves the problem.

Catalan would be the only lang affected as it has an apostrophe on VPL_COMPILATIONFAILED. Spanish and English works well.

Thank you!

**Comment by jcrodriguez-dis** [comment]
Hello Mario,
yes, it seems to be a bug that arise when the string VPL_COMPILATIONFAILED for a language ( as Catalan) has some apostrophe.
I will try to give a good solution as soon as posible.

Best regards.
Juan Carlos

**Comment by jcrodriguez-dis** [comment]
Hello Mario,
the problem has been resolved using PHP addslashes function. The VPL updated version can be download from here as v3.1.4
Best regards.
Juan Carlos

**Comment by mariocav** [comment]
Thank you very much.
