### ISSUE TITLE
Problem rendering latex equations in the description tab

### ISSUE THREAD

**Issue by fbolgar** [jcrodriguez-dis/moodle-mod_vpl#80]
Hello,

I have an issue which is similar to this one:
https://github.com/jcrodriguez-dis/moodle-mod_vpl/issues/63
Indeed, I use mathjax for equation rendering in the description of the activity, and when I open the editing tool, the description tab is shown properly, with equations rendered nicely.
However, as soon as I click on "run", "evaluate" or other, the mathjax filter goes off in the description tab, and only the tex notation filter remains.

It would not be a big problem, if the tex notation filter was actually working properly in the description tab. However, this is not the case, there is a kind of linestroke through all equations, which appears only in the description tab: if I disable mathjax at all, the equations show properly in the description page, but not in the description tab.

The problem is more clear with images:
First picture: just when opening the "edit" tab, everything works fine
![with_mathjax](https://user-images.githubusercontent.com/48879066/54877670-d5d67600-4e21-11e9-8b5c-ef2a7fa2232f.png)

Second picture: after clicking on the "run" button, the mathjax filter goes off, and the tex notation filter does not work well.
![without_mathjax](https://user-images.githubusercontent.com/48879066/54877669-d53ddf80-4e21-11e9-86a2-a56f7574d181.png)

Third picture: I tried disabling the mathjax filter, then the equations in the description page show properly without linestroke (but still not in the description page !)
![description_page_without_mathjax](https://user-images.githubusercontent.com/48879066/54877730-9a887700-4e22-11e9-955d-db9f04f72f35.png)

Fourth picture: In case, here is a picture of the filters I use.
![filters](https://user-images.githubusercontent.com/48879066/54877668-d4a54900-4e21-11e9-8f84-15e93ae04f9e.png)

Last thing to say: the images themselves are properly shown by the filter (as I can see by clicking on "show image"), so the linestroke must somehow be added afterwards.

**Comment by jcrodriguez-dis** [comment]
Hi,
This issue will be solved in the next bugfix release of VPL.

Best regards,
Juan Carlos.

**Comment by fbolgar** [comment]
Hi,

Thank you very much for your reply, and for the work you are doing with VPL: its an amazing tool !

Best regards,

**Comment by jcrodriguez-dis** [comment]
Resolved in VPL 3.3.5 just released
