### ISSUE TITLE
support moodle 3.6

### ISSUE THREAD

**Issue by jharej** [jcrodriguez-dis/moodle-mod_vpl#81]
Hi,

is there support for Moodle 3.6 planned in near future?

bye
Janko

**Comment by jcrodriguez-dis** [comment]
Hi Al.
I think that you are asking me to mark VPL as compatible with the last Moodle version. I apologize, I did not know that this may be a problem. VPL is compatible with Moodle 3.6. I will try to upload a new VPL version this week and keep updating in the next future.

Best regards,
Juan Carlos.

**Comment by jharej** [comment]
Hi,
Moodle 3.7 is out quite for a while ...  Is VPL ready to run on Moodle 3.7? Should I download the code from https://moodle.org/plugins/pluginversions.php?plugin=mod_vpl or from github?

Thanks for the answers
Janko

**Comment by jcrodriguez-dis** [comment]
Hi Janko,
Yes, VPL is ready to run on Moodle 3.7
Please, dowload the official version from Moodle.

For testing you can:
Use https://github.com/jcrodriguez-dis/moodle-mod_vpl/tree/v3.3.5?files=1
Or https://github.com/jcrodriguez-dis/moodle-mod_vpl/tree/v3.4dev?files=1
Comments are wellcome
