### ISSUE TITLE
Add ability to create user exceptions to due dates (Enhancement)

### ISSUE THREAD

**Issue by danawortman** [jcrodriguez-dis/moodle-mod_vpl#83]
It would be great to have the ability to add individual user (or group) exceptions to the due-date for labs like in normal assignments.  Sometimes students simply need more time.  I've also been using these to allow students to submit their homework and auto-evaluate it, which has saved me a tremendous amount of time in grading functionality (now I just focus on design).

**Comment by jcrodriguez-dis** [comment]
Hi Dana,
thanks for your enhancement request.
Notice that you can manage this situation using the "access restrictions" provided by Moodle. This common feature in activities can restrict the access to each activity with a complex logic as you can see in the picture.

Best regards.

----

**Restrict access adding/editing a Virtual Programming Lab activity.**
![imagen](https://user-images.githubusercontent.com/2072039/60349757-1e21a900-99ba-11e9-87d6-a9ecceea2e85.png)

----

**Restricting access for two different groups with a different due date.**
![imagen](https://user-images.githubusercontent.com/2072039/60349334-4a88f580-99b9-11e9-93f7-9972d9db41ae.png)

**Comment by danawortman** [comment]
@jcrodriguez-dis Thank you for the feedback.  Unfortunately, many of the other moodle blocks and plugins rely on due-dates to indicate completion and track progress and most importantly, STUDENTS CAN'T SEE THE RESTRICTIONS, so they are meaningless in terms of giving students an extended due-date (or a due-date at all!!).

For example, the eTask collapsible topics format relies on due dates to show students when things are due (restrictions do not show up on the progress bar for eTasks):

![image](https://user-images.githubusercontent.com/2523003/60410252-9a67e800-9b84-11e9-9102-a7d470220f99.png)

The calendar needs a due date to show on the calendar block so that students are aware that something is due (restrictions do not show up on the calendar in any way):

![image](https://user-images.githubusercontent.com/2523003/60410290-d13dfe00-9b84-11e9-890d-bc4348c9660c.png)

The due date is the standard moodle element that indicates when an assignment is completed and it would be reasonable for the VPL to model its due date system in the same way that both assignments and quizzes do, by including the standard user and group overrides.

Even worse, students cannot see restrictions anywhere in the VPL or on the main course page, making it so that they don't even know their own deadlines:

Student View:
![image](https://user-images.githubusercontent.com/2523003/60410543-21699000-9b86-11e9-9c41-865eb6b7e05a.png)

Admin View:
![image](https://user-images.githubusercontent.com/2523003/60410554-27f80780-9b86-11e9-8646-6746a3518e68.png)

I understand that a similar option is available via group-based restrictions, however, I have 23+ labs in my course and I have 4 courses, meaning that I have about 100 labs each semester and to create a group for each student who requires an override for each lab, is about 5 more steps than is feasible given that I have at least one exception in every lab.  The fact that students can't see these restriction dates is unacceptable in terms of being a solution.

I'd like to actually have concrete due dates so that students are aware of those dates and so that I can coordinate those dates with the many other blocks and plugins that I use to help my students better keep track of their assignments, labs, and other due dates.  Students need to have due-dates up-front and easy to see, find, and reference or they get confused.  I run my classes mostly as a hybrid class, so I simply don't have time in class to constantly be reminding students when things are due - that's the whole reason that I use an LMS to begin with - so that students can keep track of their own deadlines 24-7-365 and don't have to ask me constantly when things are due.

**Comment by jcrodriguez-dis** [comment]
Dear @danawortman,

To address this, we have introduced an override feature in VPL 3.5.0, courtesy of @astor-bizard, which should simplify the process of handling exceptions. More importantly, we have also added full support for the calendar in VPL 4.0.1, which should make due dates much more visible and easier to manage for both you and your students.
