### ISSUE TITLE
CSS problem

### ISSUE THREAD

**Issue by t-schroeder** [jcrodriguez-dis/moodle-mod_vpl#84]
Elements with the class "vpl_sim11" have both `color: #fff;` and `background-color: #fff;` so you can't read the text. This isn't a problem on master at the moment, but on v3.4dev for example.
![vpl-css-error](https://user-images.githubusercontent.com/24255259/62135071-dd32f200-b2e1-11e9-825b-8ef886df67d2.PNG)

**Comment by jcrodriguez-dis** [comment]
Hi Tim,
yes it is a bug. I will change the css to use other color for text.
Best regards,
Juan Carlos.

**Comment by jcrodriguez-dis** [comment]
Resolved in VPL 3.3.5 just released
