### ISSUE TITLE
Missing return statement in vpl_evaluate.cpp function Tools::getenv

### ISSUE THREAD

**Issue by mwehr** [jcrodriguez-dis/moodle-mod_vpl#86]
Hi,

We found a small bug in "vpl/jail/default_scripts/vpl_evaluate.cpp" 
function: Tools::getenv.
This function is missing a return statement: "return value;"

regards
Mario

**Comment by jcrodriguez-dis** [comment]
Resolved in VPL 3.3.5 just released
