### ISSUE TITLE
Undefined property: evaluatescript in vpl_submission_CE.class.php

### ISSUE THREAD

**Issue by cdaly2** [jcrodriguez-dis/moodle-mod_vpl#88]
Hello,

I am using moodle 3.7.2 and VPL 3.3.4 and everything seems to work well but

I am getting the following error in my apache2 error logs:
Undefined property: stdClass::$evaluatescript in /var/www/html/moodle/mod/vpl/vpl_submission_CE.class.php on line 131

Thank you.

**Comment by jcrodriguez-dis** [comment]
This bug has been resolved in V3.3.5
