### ISSUE TITLE
Graders can't create private copies of submissions

### ISSUE THREAD

**Issue by t-schroeder** [jcrodriguez-dis/moodle-mod_vpl#94]
We have the following case: Teachers manage the VPL activities. They get the capabiliy mod/vpl:manage. Tutors evaluate the students' submissions. Therefore they want to be able to modify a submission and see if it passes the test cases with that modification. This is possible by clicking on the "copy" link on the grade page for a submission. But you can only do this with the capability mod/vpl:manage. If we give that to tutors, however, they can also change the requested files, execution files, test cases etc.

It would be nice if there was a separate capability only for being able to test changes to a submission without changing the submission itself.

**Comment by jcrodriguez-dis** [comment]
It is clear that a maybe good that an evaluator that now can read the students' code also can copy it and test changes as the mod/vpl:manage capability allows. This functionality does not add new privileges to the current mod/vpl:grade capability. Now the user with mod/vpl:grade capability can manually copy the students' code and does the changes and tests in another activity.  I think we don't need a new capability, I think that we need to allow users with mod/vpl:grade capability to copy/change/test code easily.
Thanks for your comment. I add this feature to the TODO list. I hope to resolve it for the next release.

**Comment by t-schroeder** [comment]
I agree. There shouldn't be a new capability.

I've provided a fix for this based on v3.3.5. Hope that helps.

**Comment by jcrodriguez-dis** [comment]
Thanks @t-schroeder,
I 'll review it.
