### ISSUE TITLE
Test activity doesn't work for graders after due date

### ISSUE THREAD

**Issue by t-schroeder** [jcrodriguez-dis/moodle-mod_vpl#96]
People who have "mod/vpl:grade" but don't have "mod/vpl:manage" can't edit anything in the "Test activity" tab. I think this is a bug because graders can already use the Test activity before the due date. They should be able to use it afterwards as well.

With #95 graders can edit private copies of submissions after the due date has passed. But that pull request doesn't fix this problem where the "Test activity" itself is not usable after the due date.

**Comment by jcrodriguez-dis** [comment]
The issue has been resolved in a previous release. However, the fix will not take effect if you upgrade and don't reset the VPL permissions.
